Working on GSSlider
gluestack/gluestack-ui-flutter pull request #267
Opened 2024-07-09 13:12 UTC by singlapriyanka315

2024-07-10 05:53 UTC, geekykrishna requested changes
It's missing storybook implementation, do add that as well.

2024-07-17 05:38 UTC, singlapriyanka315 commented
> It's missing storybook implementation, do add that as well.

Okay @Krishnagopal-Sinha .

2024-07-17 09:00 UTC, geekykrishna approved these changes

2024-07-22 06:55 UTC, geekruchika commented on lib/src/utils/resolver.dart
> +// Map<String, GSConfigStyle>? resolveCompoundVariants(
cleanup

2024-07-22 07:25 UTC, singlapriyanka315 commented on lib/src/utils/resolver.dart
> +// Map<String, GSConfigStyle>? resolveCompoundVariants(
Sure .

2024-07-22 07:55 UTC, merged